# Generated by Django 4.1.5 on 2023-02-12 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Категории')),
                ('img', models.ImageField(blank=True, null=True, upload_to='image_category', verbose_name='Фото')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL')),
            ],
        ),
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Содержание')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='edition')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('is_published', models.BooleanField(default=True, verbose_name='Публикация')),
                ('relation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='max.category', verbose_name='Категории')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
                'ordering': ['-slug'],
            },
        ),
    ]
