# Generated by Django 4.1.5 on 2023-03-13 16:03

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('max', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='edition',
            options={'ordering': ['-slug'], 'verbose_name': 'Книгу', 'verbose_name_plural': 'Книги'},
        ),
        migrations.AlterField(
            model_name='edition',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='edition', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='edition',
            name='slug',
            field=autoslug.fields.AutoSlugField(max_length=255, unique=True, verbose_name='URL'),
        ),
    ]
