# Generated by Django 4.1.5 on 2023-03-22 21:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('max', '0002_alter_category_options_alter_edition_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='category', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='edition',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Время создания'),
        ),
    ]
