# Generated by Django 4.1.5 on 2023-03-22 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('max', '0003_alter_category_img_alter_edition_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='../max/static/max/category', verbose_name='Фото'),
        ),
    ]
