# Generated by Django 4.1.5 on 2023-03-22 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('max', '0004_alter_category_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='max/static/max/category', verbose_name='Фото'),
        ),
    ]
